sudo: required
language: node_js
node_js:
  - 'stable'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.10'
before_script:
  - find test -type d -exec chmod g+s {} \;
  - sudo chown root test/not-owned/
  - sudo chown root test/not-owned/not-owned.txt
after_script:
  - npm run coveralls
